#!/usr/bin/env python3
"""Build a Jenkins controller VM on an XCP-ng host, from a Debian cloud image.

The plugin needs a controller the provisioned agents can reach. An agent dials *out* over a
WebSocket (see image/provision.sh) and fetches agent.jar from the controller's root URL, so
the controller has to sit somewhere the pool's guests can route to. A controller on a
developer workstation behind WSL2's NAT cannot be reached at all, which is what this script
exists to avoid: it puts one on the lab LAN in a few minutes, reproducibly.

Three things about the VM's identity are one-shot, and getting any of them wrong means a
rebuild rather than a fix:

  * cloud-init applies network-config *per instance*, so addressing only lands on first boot;
  * an HVM CD-ROM cannot be hotplugged (VBD.plug returns OPERATION_NOT_ALLOWED, and a reboot
    is not enough either -- only a full stop/start attaches it), so the guest-tools ISO has
    to be attached before the VM is first started;
  * a DHCP lease is keyed on the MAC, and VM.clone regenerates an autogenerated one, so
    leaving the MAC blank hands the VM a new address on every rebuild.

Addressing is DHCP by default and deliberately so. The guest tools make XAPI report the
address, so nothing here needs to know the subnet, the DHCP pool boundaries, or anything
about the router. A static address is available for operators who know their network, but it
is not the default: an address that is free today and inside the DHCP pool tomorrow is the
one failure this script cannot detect for you. Sites that want a reservation can pass
--reservation-hook; DHCP servers have nothing in common at the API level, so vendor code
lives in the hook rather than here.

Re-running destroys and rebuilds the VM of the same name, and sweeps VDIs a previous failed
run left behind, so it is safe to iterate on.

    XCPNG_HOST=192.168.1.98 XCPNG_USER=root XCPNG_PASS=... XCPNG_TRUST_SELF_SIGNED=1 \
        python3 tools/build_controller.py --pubkey ~/.ssh/id_ed25519.pub
"""

import argparse
import hashlib
import pathlib
import subprocess
import sys
import tempfile
import time
import urllib.request

from xapi import Xapi, XapiError

IMAGE_URL = "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2"
SUMS_URL = "https://cloud.debian.org/images/cloud/trixie/latest/SHA512SUMS"
DOCKER_KEY_URL = "https://download.docker.com/linux/debian/gpg"

# Xensource's registered OUI. Deriving a MAC inside it keeps the address stable across
# rebuilds without colliding with a real vendor's range.
XEN_OUI = "00:16:3e"


def stable_mac(name):
    """A deterministic MAC for a VM name, inside Xen's OUI.

    A DHCP server keys its lease on the MAC, so a stable MAC brings a rebuilt VM back on the
    same address with no router configuration at all. Leaving it to XAPI does the opposite:
    VM.clone regenerates an autogenerated MAC, so every rebuild moves.
    """
    digest = hashlib.sha256(name.encode()).digest()
    # Clear the top bit of the first derived octet purely to keep the value inside the range
    # XenServer itself uses; nothing depends on it beyond staying conventional.
    return "%s:%02x:%02x:%02x" % (XEN_OUI, digest[0] & 0x7F, digest[1], digest[2])


def network_config(address, gateway, nameserver):
    """cloud-init v2 network config.

    Matches on ``en*`` rather than naming an interface: under Xen the NIC comes up as enX0,
    not eth0, and a config that names the wrong interface produces a VM with no network and
    no way in.
    """
    if address == "dhcp":
        return 'version: 2\nethernets:\n  primary:\n    match:\n      name: "en*"\n    dhcp4: true\n'
    return (
        "version: 2\n"
        "ethernets:\n"
        "  primary:\n"
        '    match:\n      name: "en*"\n'
        "    dhcp4: false\n"
        f"    addresses: [{address}]\n"
        f"    routes:\n      - to: default\n        via: {gateway}\n"
        f"    nameservers:\n      addresses: [{nameserver}]\n"
    )


def user_data(name, pubkey, docker_key):
    """cloud-init user-data: the debian user, the guest tools, then Docker."""
    indented = "\n".join(
        "      " + line if line else "" for line in docker_key.split("\n")
    )
    return f"""#cloud-config
hostname: {name}
fqdn: {name}.lan
manage_etc_hosts: true
preserve_hostname: false

users:
  - name: debian
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: true
    ssh_authorized_keys:
      - {pubkey}

package_update: true
packages:
  - ca-certificates
  - curl

write_files:
  - path: /etc/apt/keyrings/docker.asc
    permissions: '0644'
    owner: root:root
    content: |
{indented}

runcmd:
  # XCP-ng guest tools. xe-guest-utilities is not in Debian's repositories, so the ISO is the
  # only route, and without the tools XAPI reports networks={{}} forever: neither XO nor this
  # script can see the guest's address. Install the .deb directly rather than running
  # Linux/install.sh, because dpkg's exit code is meaningful.
  - [ sh, -c, "mkdir -p /mnt/tools && mount -o ro /dev/sr0 /mnt/tools" ]
  - [ sh, -c, "dpkg -i /mnt/tools/Linux/xe-guest-utilities_*_amd64.deb > /var/log/guest-tools-install.log 2>&1" ]
  - [ sh, -c, "umount /mnt/tools || true" ]

  # Docker from Docker's own repository. An ASCII-armored key at a signed-by path means no
  # gpg binary is needed to dearmor anything, which matters on a minimal cloud image.
  - [ install, -m, '0755', -d, /etc/apt/keyrings ]
  - [ sh, -c, "printf 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian trixie stable\\n' > /etc/apt/sources.list.d/docker.list" ]
  - [ apt-get, update ]
  - [ sh, -c, "DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin" ]
  - [ systemctl, enable, --now, docker ]
  - [ usermod, -aG, docker, debian ]

  # A build record worth reading. xe-daemon has no --version flag, so ask dpkg, and say so
  # loudly when the tools are absent rather than leaving a blank line that reads like success.
  - [ sh, -c, "docker --version > /var/log/build-ready 2>&1; docker compose version >> /var/log/build-ready 2>&1" ]
  - [ sh, -c, "dpkg-query -W xe-guest-utilities >> /var/log/build-ready 2>&1 || echo 'guest tools NOT installed' >> /var/log/build-ready" ]

final_message: "cloud-init done after $UPTIME seconds"
"""


def build_seed(workdir, name, pubkey, address, gateway, nameserver, docker_key):
    """Write a NoCloud seed and package it as an iso9660 labelled cidata.

    Attached as an ordinary disk, not a CD: cloud-init finds the datasource by filesystem
    label, and a plain disk sidesteps the rule that an HVM CD cannot be hotplugged.
    """
    seed = workdir / "seed"
    seed.mkdir(exist_ok=True)
    (seed / "meta-data").write_text(
        f"instance-id: {name}-001\nlocal-hostname: {name}\n"
    )
    (seed / "network-config").write_text(network_config(address, gateway, nameserver))
    (seed / "user-data").write_text(user_data(name, pubkey, docker_key))

    iso = workdir / "seed.iso"
    subprocess.run(
        [
            "genisoimage",
            "-quiet",
            "-output",
            str(iso),
            "-volid",
            "cidata",
            "-joliet",
            "-rock",
            str(seed / "user-data"),
            str(seed / "meta-data"),
            str(seed / "network-config"),
        ],
        check=True,
    )
    return iso


def fetch_image(workdir):
    """Download the cloud image, verify it, convert it to raw.

    The checksum is not optional. A corrupt image surfaces as a VM that will not boot, which
    looks exactly like a firmware problem and costs an afternoon to tell apart.
    """
    qcow = workdir / "debian-13-genericcloud-amd64.qcow2"
    raw = workdir / "debian-13-genericcloud-amd64.raw"
    urllib.request.urlretrieve(IMAGE_URL, qcow)

    sums = urllib.request.urlopen(SUMS_URL, timeout=60).read().decode()
    want = next(
        line.split()[0] for line in sums.splitlines() if line.endswith(qcow.name)
    )
    if hashlib.sha512(qcow.read_bytes()).hexdigest() != want:
        raise SystemExit(f"checksum mismatch for {qcow.name}; refusing to import it")
    print("  sha512 OK")

    subprocess.run(
        ["qemu-img", "convert", "-f", "qcow2", "-O", "raw", str(qcow), str(raw)],
        check=True,
    )
    return raw


def import_vdi(x, sr, path, name, virtual_size=None):
    """Create a VDI and stream a raw image into it over import_raw_vdi.

    ``virtual_size`` may exceed the image: the tail is zeroes, and growpart expands the root
    filesystem into it on first boot. Sizing the VDI up front rather than calling VDI.resize
    afterwards is deliberate -- a resize straight after an import fails VDI_IN_USE, because
    the import has not finished releasing the disk.
    """
    size = path.stat().st_size
    vdi = x.call(
        "VDI.create",
        {
            "name_label": name,
            "name_description": "built by tools/build_controller.py",
            "SR": sr,
            "virtual_size": str(virtual_size or size),
            "type": "user",
            "sharable": False,
            "read_only": False,
            "other_config": {},
        },
    )
    try:
        url = f"https://{x.host}/import_raw_vdi?session_id={x.session}&vdi={vdi}&format=raw"
        started = time.monotonic()
        with open(path, "rb") as fh:
            req = urllib.request.Request(url, data=fh, method="PUT")
            req.add_header("Content-Length", str(size))
            urllib.request.urlopen(req, timeout=3600, context=x._ctx)
        print(f"  imported {name} in {time.monotonic() - started:.1f}s")
    except Exception:
        # reaper.py iterates VMs, so a VDI attached to no VM leaks where nothing will find
        # it. Bootstrap code cleans up its own.
        x.call("VDI.destroy", vdi)
        raise
    return vdi


def await_void_task(x, task, poll=2, timeout=900):
    """Wait for an Async.* task that produces no OpaqueRef.

    Xapi.await_task insists the result parses as an OpaqueRef and raises
    TASK_RESULT_UNPARSEABLE for a void task such as Async.VM.start (issue #79). Until that is
    fixed this waits on the status alone. Async rather than a synchronous VM.start on
    purpose: a synchronous start blocks until the VM is up, which on a loaded host outruns
    the transport timeout while the VM carries on booting.
    """
    deadline = time.monotonic() + timeout
    while True:
        status = x.call("task.get_status", task)
        if status != "pending":
            break
        if time.monotonic() > deadline:
            raise XapiError("TASK_TIMEOUT", task)
        time.sleep(poll)
    if status != "success":
        raise XapiError(f"TASK_{status.upper()}", x.call("task.get_error_info", task))
    x.call("task.destroy", task)


def run_reservation_hook(hook, mac, name):
    """Let an external command create a DHCP reservation for our MAC, if the site has one.

    A shell-out rather than support for any particular router: consumer and enterprise DHCP
    servers share no API, and baking one vendor in would make this script useless everywhere
    else. Failure is not fatal, because the address is read back from XAPI regardless.
    """
    print(f"reservation hook: {hook} {mac} {name}")
    try:
        done = subprocess.run(
            [hook, mac, name], capture_output=True, text=True, timeout=120, check=True
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError) as exc:
        print(f"  hook failed, continuing on DHCP: {exc}", file=sys.stderr)
        return None
    reserved = done.stdout.strip()
    print(f"  hook reserved: {reserved or '(no address printed)'}")
    return reserved or None


def destroy_existing(x, name):
    """Remove a previous build of this VM, and sweep VDIs an earlier failure stranded."""
    for ref, rec in x.call("VM.get_all_records").items():
        if rec["name_label"] != name:
            continue
        if rec["is_a_template"] or rec["is_a_snapshot"] or rec["is_control_domain"]:
            continue
        print(f"destroying existing {name} ({rec['uuid']}) ...")
        if rec["power_state"] != "Halted":
            await_void_task(x, x.call("Async.VM.hard_shutdown", ref))
        # Capture the VDIs before VM.destroy: it removes the VBDs on the way out, and the
        # VDIs behind them become unreachable orphans.
        vdis = [x.call("VBD.get_VDI", b) for b in x.call("VM.get_VBDs", ref)]
        x.call("VM.destroy", ref)
        for vdi in vdis:
            if vdi == "OpaqueRef:NULL":
                continue
            label = x.call("VDI.get_name_label", vdi)
            if label.endswith(".iso"):
                continue  # shared ISO SR content, not ours to destroy
            try:
                x.call("VDI.destroy", vdi)
                print(f"  destroyed VDI {label}")
            except XapiError as exc:
                print(f"  could not destroy VDI {label}: {exc}", file=sys.stderr)

    for ref, rec in x.call("VDI.get_all_records").items():
        if (
            rec["name_label"] in ("debian-13-genericcloud", f"{name}-cidata")
            and not rec["VBDs"]
        ):
            x.call("VDI.destroy", ref)
            print(f"  swept orphan VDI {rec['name_label']}")


def find_ext_sr(x):
    """The first file-based SR. ext gets copy-on-write clones, which is what the pool is for."""
    for ref, rec in x.call("SR.get_all_records").items():
        if rec["type"] == "ext":
            return ref
    raise SystemExit("no ext SR found on this host")


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--name", default="jenkins-controller")
    p.add_argument(
        "--pubkey",
        required=True,
        help="SSH public key to authorise for the debian user",
    )
    p.add_argument(
        "--address",
        default="dhcp",
        help="'dhcp' (default) or CIDR, e.g. 192.168.1.99/24",
    )
    p.add_argument("--gateway", help="required with a static --address")
    p.add_argument("--nameserver", help="required with a static --address")
    p.add_argument(
        "--mac", default="", help="pin the MAC; defaults to one derived from --name"
    )
    p.add_argument(
        "--reservation-hook",
        help="command run as HOOK <mac> <name> before the VM is created, for sites that want "
        "a DHCP reservation. Failure is not fatal.",
    )
    p.add_argument(
        "--bridge", default="xenbr0", help="host bridge to attach the VIF to"
    )
    p.add_argument(
        "--template", default="Debian Trixie 13", help="stock template to clone"
    )
    p.add_argument("--memory-gib", type=int, default=4)
    p.add_argument("--vcpus", type=int, default=2)
    p.add_argument("--disk-gib", type=int, default=40)
    p.add_argument(
        "--wait", type=int, default=600, help="seconds to wait for a reported address"
    )
    args = p.parse_args(argv)

    if args.address != "dhcp":
        if "/" not in args.address:
            p.error("--address must be 'dhcp' or CIDR, e.g. 192.168.1.99/24")
        if not args.gateway or not args.nameserver:
            p.error("--gateway and --nameserver are required with a static --address")
    if not args.mac:
        args.mac = stable_mac(args.name)
    return args


def build(x, args, pubkey, docker_key):
    """Create the VM and start it. Returns its VM ref."""
    destroy_existing(x, args.name)
    sr = find_ext_sr(x)

    tools_iso = None
    for ref, rec in x.call("VDI.get_all_records").items():
        if rec["name_label"] == "guest-tools.iso":
            tools_iso = ref
            break
    if tools_iso is None:
        print(
            "warning: guest-tools.iso not found in any ISO SR. The VM will have no in-guest "
            "agent, so XAPI will never report its address.",
            file=sys.stderr,
        )

    with tempfile.TemporaryDirectory(prefix="controller-build-") as td:
        workdir = pathlib.Path(td)
        raw = fetch_image(workdir)
        seed_iso = build_seed(
            workdir,
            args.name,
            pubkey,
            args.address,
            args.gateway,
            args.nameserver,
            docker_key,
        )
        root_vdi = import_vdi(
            x, sr, raw, "debian-13-genericcloud", virtual_size=args.disk_gib * 1024**3
        )
        seed_vdi = import_vdi(x, sr, seed_iso, f"{args.name}-cidata")

    template = None
    for ref, rec in x.call("VM.get_all_records").items():
        if rec["is_a_template"] and rec["name_label"] == args.template:
            template = ref
            break
    if template is None:
        raise SystemExit(f"template {args.template!r} not found on this host")

    # Cloning a stock template is what makes UEFI work here. XAPI initialises the varstore on
    # the first start of a template-provisioned VM, so a raw-imported cloud image boots with
    # no NVRAM seeding at all -- measured on this pool, NVRAM {} before, ['EFI-variables']
    # after. Building the VM from scratch with VM.create is the case that needs a seeded
    # varstore.
    vm = x.call("VM.clone", template, args.name)
    x.call("VM.set_is_a_template", vm, False)
    x.call(
        "VM.add_to_other_config", vm, "lab-purpose", "jenkins-controller-docker-host"
    )
    memory = str(args.memory_gib * 1024**3)
    x.call("VM.set_memory_limits", vm, memory, memory, memory, memory)
    x.call("VM.set_VCPUs_max", vm, str(args.vcpus))
    x.call("VM.set_VCPUs_at_startup", vm, str(args.vcpus))

    for device, vdi in ((0, root_vdi), (1, seed_vdi)):
        x.call(
            "VBD.create",
            {
                "VM": vm,
                "VDI": vdi,
                "userdevice": str(device),
                "bootable": device == 0,
                "mode": "RW",
                "type": "Disk",
                "empty": False,
                "other_config": {},
                "qos_algorithm_type": "",
                "qos_algorithm_params": {},
            },
        )
    if tools_iso is not None:
        x.call(
            "VBD.create",
            {
                "VM": vm,
                "VDI": tools_iso,
                "userdevice": "3",
                "bootable": False,
                "mode": "RO",
                "type": "CD",
                "empty": False,
                "other_config": {},
                "qos_algorithm_type": "",
                "qos_algorithm_params": {},
            },
        )

    network = None
    for ref, rec in x.call("network.get_all_records").items():
        if rec["bridge"] == args.bridge:
            network = ref
            break
    if network is None:
        raise SystemExit(f"no network on bridge {args.bridge!r}")
    x.call(
        "VIF.create",
        {
            "VM": vm,
            "network": network,
            "device": "0",
            "MAC": args.mac,
            "MTU": "1500",
            "other_config": {},
            "qos_algorithm_type": "",
            "qos_algorithm_params": {},
        },
    )

    await_void_task(x, x.call("Async.VM.start", vm, False, False))
    return vm


def wait_for_address(x, vm, timeout):
    """Poll the guest metrics until the in-guest agent reports an address.

    This is the only end-to-end proof that the guest tools installed: without them the record
    stays empty however healthy the VM is.
    """
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        metrics = x.call("VM.get_guest_metrics", vm)
        if metrics != "OpaqueRef:NULL":
            networks = x.call("VM_guest_metrics.get_networks", metrics)
            if networks:
                return networks
        time.sleep(15)
    return {}


def main(argv=None):
    args = parse_args(argv)
    pubkey = pathlib.Path(args.pubkey).expanduser().read_text().strip()
    print(f"MAC: {args.mac}")
    if args.reservation_hook:
        run_reservation_hook(args.reservation_hook, args.mac, args.name)

    docker_key = (
        urllib.request.urlopen(DOCKER_KEY_URL, timeout=60).read().decode().rstrip("\n")
    )

    with Xapi() as x:
        vm = build(x, args, pubkey, docker_key)
        print(f"{args.name} uuid={x.call('VM.get_uuid', vm)} address={args.address}")
        print(f"  NVRAM after start: {list(x.call('VM.get_NVRAM', vm)) or '{}'}")

        networks = wait_for_address(x, vm, args.wait)
        if networks:
            print(f"  reported address: {networks.get('0/ip', networks)}")
        else:
            print(
                "  no address reported. Check /var/log/guest-tools-install.log in the guest: "
                "without the tools XAPI cannot see the address even if the VM is healthy.",
                file=sys.stderr,
            )
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
